### PR TITLE
Milestone 1 project initialization and setup

### PR DESCRIPTION
**Pull request by descholar-ceo**
## What does this PR do?
It initializes and sets the project

## Tasks to be completed on this PR
- [x] Use create-react-app to initialize a new React app
- [x] Delete any unnecessary file or asset
- [x] Install dependencies  `prop-types` and `big.js`
- [x] Install linters (eslint and stylelint)
- [x] Deployment to heroku

## Link to heroku
[Visit the calculator to heroku](https://descholar-calculator-react.herokuapp.com/)

## Question
I was having issue with deploying this project to heroku. See the error I was getting on the screenshot below :point_down: 
Screenshot from 2020-12-04 16-01-09
As a temporary solution, I moved the following dependencies: `eslint`, `eslint-config-airbnb`, `eslint-plugin-import`, `eslint-plugin-jsx-a11y`, `eslint-plugin-react`, and `eslint-plugin-react-hooks` from `devDependencies` to `dependencies` while I am still looking for a proper solution. Any help would be appreciated! :pray:

### CODE REVIEW

**Comment by bellom** [comment]
> ## What does this PR do?
> It initializes and sets the project
> 
> ## Tasks to be completed on this PR
> * [x]  Use create-react-app to initialize a new React app
> * [x]  Delete any unnecessary file or asset
> * [x]  Install dependencies  `prop-types` and `big.js`
> * [x]  Install linters (eslint and stylelint)
> * [x]  Deployment to heroku
> 
> ## Link to heroku
> [Visit the calculator to heroku](https://descholar-calculator-react.herokuapp.com/)
> 
> ## Question
> I was having issue with deploying this project to heroku. See the error I was getting on the screenshot below 👇
> Screenshot from 2020-12-04 16-01-09
> As a temporary solution, I moved the following dependencies: `eslint`, `eslint-config-airbnb`, `eslint-plugin-import`, `eslint-plugin-jsx-a11y`, `eslint-plugin-react`, and `eslint-plugin-react-hooks` from `devDependencies` to `dependencies` while I am still looking for a proper solution. Any help would be appreciated! 🙏

I try to reproduce the error, seems working fine.

But let me also try to push to Heroku, I will get back to you.

And we can jump on a call if you're available


**Quick One:**
You added some scripts in `package.json`;
If I may ask, why did you add them?
image

**Review by bellom — APPROVED** [review]
## Hi @descholar-ceo :clap: 

##### You have done wonderfully well

I will keep looking into the issue, let me know when you're online.

Project approved but let's solve the issue before moving on.

# Status: Approved 👍 


**Best,**

**Oluwaseun J. Bello**
**_Slack Handle - @sean bellom_**

**Comment by descholar-ceo** [comment]
> > ## What does this PR do?
> > It initializes and sets the project
> > ## Tasks to be completed on this PR
> > 
> > * [x]   Use create-react-app to initialize a new React app
> > * [x]   Delete any unnecessary file or asset
> > * [x]   Install dependencies  `prop-types` and `big.js`
> > * [x]   Install linters (eslint and stylelint)
> > * [x]   Deployment to heroku
> > 
> > ## Link to heroku
> > [Visit the calculator to heroku](https://descholar-calculator-react.herokuapp.com/)
> > ## Question
> > I was having issue with deploying this project to heroku. See the error I was getting on the screenshot below point_down
> > Screenshot from 2020-12-04 16-01-09
> > As a temporary solution, I moved the following dependencies: `eslint`, `eslint-config-airbnb`, `eslint-plugin-import`, `eslint-plugin-jsx-a11y`, `eslint-plugin-react`, and `eslint-plugin-react-hooks` from `devDependencies` to `dependencies` while I am still looking for a proper solution. Any help would be appreciated! pray
> 
> I try to reproduce the error, seems working fine.
> 
> But let me also try to push to Heroku, I will get back to you.
> 
> And we can jump on a call if you're available
> 
> **Quick One:**
> You added some scripts in `package.json`;
> If I may ask, why did you add them?
> image

Hello @bellom, thank you for your kind review and feedback, the following is the answers to the questions you asked me in the feedback you gave me:
1. The scripts `eslint-f` and `stylelint-f` I added them to oackage.json file, for the sake of my productivity during development while I want to run linters fix, so just added those scripts so that I can just type a simple memorable word and it works
2. About the error, I get that error when the app is deployed and trying to access it, then it throws that error to the user. That's why I used [this solution from stackoverflow](https://stackoverflow.com/questions/47717115/heroku-app-crashed-because-of-eslint-faulty-import). I am now available we can set up a meeting.

**Comment by descholar-ceo** [comment]
@bellom I will merge this PR to be able to continue working on the next tasks. I have opened [this issue #2 ](https://github.com/descholar-ceo/calculator-react/issues/2). So that after we talk or find any other solution, I will open a bug fix PR to close that issue.

Thank you!

**Pull request merged**
